# Generated by Django 4.1.4 on 2022-12-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_blog_tags_blog_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="breif_info",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
